### ISSUE TITLE
ARM64 version

### ISSUE THREAD

**Issue by JanJans640** [crocandr/docker-softether#1]
Hi, Is it possible to create a ARM64 version of your container?
Thanks in advance.
Jan

**Comment by crocandr** [comment]
Hi,

Thanks!
I see arm64 binary is available too (example: https://www.softether-download.com/files/softether/v4.39-9772-beta-2022.04.26-tree/Linux/SoftEther_VPN_Server/64bit_-_ARM_64bit/ ), so I will create arm image too. ;)
But I don’t have too much free time, but I will do as soon as possible.

Thanks for your patience!

**Comment by JanJans640** [comment]
Hi Andras,

Thanks for your fast response.
No problem. I can wait.

Best regards.

**Comment by crocandr** [comment]
Hi,

I don’t have any arm64 device, so I can’t test it, but I built one with docker buildx method:
https://hub.docker.com/r/croc/softether-arm64/tags

Please try it! If you get any problem with the container, please, let me know!

I hope it will work :)

Have a nice day! :)

**Comment by JanJans640** [comment]
I will as soon I have my Raspberry pi in house.
Unfortunately its delayed again, due to components shortage.
Thanks for you super fast response

Rgds.

**Comment by JanJans640** [comment]
Hi Andras,

I have tested the new ARM64 image, and it is working perfectly.
Thank you very much for making this image.
I hope it will get regular updates too like the AMD64 image.
Best regards,
Jan
